"""Modulo de preprocessamento para normalizacao de eventos de entrada."""

from app.preprocessing.audio_transcription import (
    AudioAttachmentNotFoundError,
    AudioDownloadError,
    AudioTranscriber,
    AudioTranscription,
    AudioTranscriptionError,
    OpenAIAudioTranscriber,
    UnsupportedAudioTranscriptionProviderError,
    build_audio_transcriber,
    transcribe_audio_event,
)
from app.preprocessing.image_analysis import (
    GoogleImageAnalyzer,
    ImageAnalysis,
    ImageAnalysisError,
    ImageAnalyzer,
    ImageAttachmentNotFoundError,
    ImageDownloadError,
    UnsupportedImageAnalysisProviderError,
    analyze_image_event,
    build_image_analyzer,
)
from app.preprocessing.message_composer import (
    ComposedAgentInput,
    ComposerSource,
    MessageCompositionError,
    SOURCE_PRIORITY,
    compose_agent_input,
)
from app.preprocessing.pdf_processing import (
    PdfAttachmentNotFoundError,
    PdfDownloadError,
    PdfProcessing,
    PdfProcessingError,
    PdfProcessor,
    PyPdfProcessor,
    UnsupportedPdfProcessingProviderError,
    build_pdf_processor,
    process_pdf_event,
)
from app.preprocessing.event_normalizer import (
    EventNormalizationError,
    NormalizedAttachment,
    NormalizedIncomingEvent,
    normalize_incoming_event,
)

__all__ = [
    "AudioAttachmentNotFoundError",
    "AudioDownloadError",
    "AudioTranscriber",
    "AudioTranscription",
    "AudioTranscriptionError",
    "EventNormalizationError",
    "GoogleImageAnalyzer",
    "ImageAnalysis",
    "ImageAnalysisError",
    "ImageAnalyzer",
    "ImageAttachmentNotFoundError",
    "ImageDownloadError",
    "MessageCompositionError",
    "NormalizedAttachment",
    "NormalizedIncomingEvent",
    "OpenAIAudioTranscriber",
    "PdfAttachmentNotFoundError",
    "PdfDownloadError",
    "PdfProcessing",
    "PdfProcessingError",
    "PdfProcessor",
    "PyPdfProcessor",
    "SOURCE_PRIORITY",
    "UnsupportedImageAnalysisProviderError",
    "UnsupportedPdfProcessingProviderError",
    "UnsupportedAudioTranscriptionProviderError",
    "analyze_image_event",
    "build_audio_transcriber",
    "build_image_analyzer",
    "build_pdf_processor",
    "compose_agent_input",
    "ComposedAgentInput",
    "ComposerSource",
    "normalize_incoming_event",
    "process_pdf_event",
    "transcribe_audio_event",
]
